"""init public schema

Revision ID: 709af6d55444
Revises: c1a07cc34522
Create Date: 2026-03-30 00:54:10.252628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '709af6d55444'
down_revision: Union[str, Sequence[str], None] = 'c1a07cc34522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('schema_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='public'
    )
    op.create_index(op.f('ix_public_tenant_id'), 'tenant', ['id'], unique=False, schema='public')
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email_id', sa.String(length=50), nullable=True),
    sa.Column('hashed_pwd', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenant.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email_id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_users_user_id'), 'users', ['user_id'], unique=False, schema='public')
    op.create_table('user_session',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.LargeBinary(length=32), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_user_session_session_id'), 'user_session', ['session_id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_user_session_session_id'), table_name='user_session', schema='public')
    op.drop_table('user_session', schema='public')
    op.drop_index(op.f('ix_public_users_user_id'), table_name='users', schema='public')
    op.drop_table('users', schema='public')
    op.drop_index(op.f('ix_public_tenant_id'), table_name='tenant', schema='public')
    op.drop_table('tenant', schema='public')
    # ### end Alembic commands ###
